SOURCES = $(SLIDES_DIR)/00-title.md \
          $(SLIDES_DIR)/01-design-thinking.md \
          $(SLIDES_DIR)/02-feature-design.md \
          $(SLIDES_DIR)/03-quality.md

include $(shell git rev-parse --show-toplevel)/themes/ufo-beamer/ufo-beamer.mk
