SOURCES = $(SLIDES_DIR)/00-title.md \
          $(SLIDES_DIR)/01-examples.md

WITH_CHANGES = true
PDF_PREFIX   = example-

include $(shell git rev-parse --show-toplevel)/themes/ufo-beamer/ufo-beamer.mk
