SOURCES = $(SLIDES_DIR)/00-title.md \
          $(SLIDES_DIR)/01-examples.md

EXTRA_VARS_TEX = \ufochangestrue
PDF_PREFIX     = example-

include $(shell git rev-parse --show-toplevel)/themes/ufo-beamer/ufo-beamer.mk
